# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Purple Dream
email: alexanderortiz.201@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alexander Ortiz's Great Blog and Portfolio Page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexortiz201.github.io" # the base hostname & protocol for your site
twitter_username: AOrtiz201
github_username:  AlexOrtiz201

# Build settings
markdown: kramdown
